### ISSUE TITLE
Test Fixtures - Set-Up and Tear-Down of Directory Structure

### ISSUE THREAD

**Issue by chrispcharlton** [chrispcharlton/trufflepig#4]
In order to test trufflepig we will need to be able to create and populate a directory tree with dummy files to search through. This could possibly be from a structure outlined by a config file or class. Whatever solution is used needs to be easily extendible (e.g. to include a variety of file types) so that future functionality can be tested.

PyTest provides a built-in [tmpdir](https://docs.pytest.org/en/stable/tmpdir.html) fixture which creates a unique directory for the duration of a test. Some wrappers around this to create specific sub-directories and files would probably do the trick. 

Directories will need to be created using something like [os.mkdir](url). Files could be created using something like [pathlib.Path.touch](https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch) or just by opening and closing files e.g. `open(fname, 'a').close()`.

An example of a test run with a fixture `test_dir` to check that `filesearchfunction` returns something could look like:
```
def test_filesearchfunction(test_dir):
    result = filesearchfunction(testdir)
    assert len(result)
```

**Comment by chrispcharlton** [comment]
@herector8 I thought you might be interested in this issue if you're interested in learning about [pytest](https://docs.pytest.org/en/stable/contents.html). This fixture will be pretty core to our test suite. I'm happy to work on this too if you're not interested (or work together if you are :hammer_and_wrench:)

**Comment by herector8** [comment]
Yeah that sounds like the perfect way for me to contribute and learn! Playing with pytest at the moment to warm up the fingers
