### ISSUE TITLE
Extracting dates from filenames?

### ISSUE THREAD

**Issue by chrispcharlton** [chrispcharlton/trufflepig#5]
We may need a function(s) that can extract dates from filenames, for example 

- report_20201012.xlsx
- report_12_10_2020.xlsx
- 2020_10_12_report.xlsx

Should all return a date of 2020-10-12.

This could let us create a function that would rename a set of files to all have the same specified date format or search for files that contain a date.

**Comment by chrispcharlton** [comment]
This could also let us do an auto-organise into time-based folders, for example (year, month)

**Comment by herector8** [comment]
Would dateutil.dparser work? That's what I have been using lately. Is it ok to have those dependencies in our package? Or are we looking to customise those features.

**Comment by chrispcharlton** [comment]
I think dateutil is fine as it's a core library, it would require a pretty big change to break it.

Looking at the [docs for parser.parse](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse) it seems there's support for extracting dates from strings while ignoring non-date components, but we would need to test if this relies on any formatting, for example spaces between tokens. 

Could be worth setting up a test with some different filename formats to see if the parser behaves as expected?

**Comment by chrispcharlton** [comment]
After looking more into `dateutil.parser` I've come to the conclusion that it's purpose is converting strings to datetime objects rather than extracting dates from text. If we want to do this I think the best way might be a library of regular expressions for supported date formats. Iterate over this list of regex until we find a match.

**Comment by herector8** [comment]
What could be done is extract the string using regex then parse it to that function or datetime.strptime for extra step handling? Would that make sense?

**Comment by chrispcharlton** [comment]
yeah, would just require a pattern for each possible format I think

**Comment by herector8** [comment]
This also has to be where @iansane has his major contribution to reviewing as a regex samurai
